### ISSUE TITLE
Interface de utilizador: Menu, comandos ou GUI?

### ISSUE THREAD

**Issue by danielcarvalhopt** [danielcarvalhopt/ProjectoLI3#1]
Qual a melhor estratégia para a interacção do utilizador com o programa?
- Através de um menu na consola, tornando as operações mais intuitivas para o utilizador através de navegação por opções.
- Comandos, podendo fazer um man interno com as descrições de cada comando.
- Interface gráfica. Caso seja possível e haja tempo poderíamos implementar uma GUI com o GTK+ por exemplo.

Qual a melhor estratégia?

**Comment by chalkos** [comment]
menu de consola - simples e poderoso
comandos - obrigavas o utilizador a saber demais só para executar um programa
interface gráfica - nao. problemas de compatibilidade, modificações no código para teres as cenas graficamente, imenso tempo perdido com isso...

conclusão: menu de consola. nem que se use algo como getchar ou assim... cenas intuitivas...
vou fazer um demo. se usares o getchar, podes mapear coisas como a tecla PgUp e PgDn.. isso ficava fixe para navegar... ou teclas de setas... ja vou ver isso.

**Comment by chalkos** [comment]
**depois de testar**
Acabei de ver que o que queria fazer é impossível.

queria navegar pelos menus usando teclas como as setas ou o **PgUp** e o **PgDn**... mas o ubuntu interpreta carregar numa seta como **^[[B** e isso escaxa. Também é necessário carregar enter.

Seja como for, estão aqui duas limitações que teremos a não ser que implementemos código especifico para determinado sistema operativo:
- receber input sem carregar em enter no fim.
- receber um input que não seja texto (caracteres especiais e teclas como as setas e o **ESC**...)

isto faz com que o menu de consola seja um pouco estático... a minha ideia era seleccionar com seta cima/baixo e expandir/esconder as subcategorias com esquerda/direita...

talvez a melhor maneira seja mesmo comandos... embora dê trabalho é mais seguro que ambiente gráfico.

**Comment by chalkos** [comment]
Falei com o gregs e pelos vistos as apresentações são no nosso pc, e não no do prof.
Ou seja, o código tem que correr nas nossas máquinas, não na máquina do prof.
Assim concluo: 85, queres que te passe a minha máquina virtual (para termos a certeza que desenvolvemos código que dê para os 2) e implementa-se um menu em que se usem as teclas de setas para navegar? (e podemos implementar muito mais coisas do ubuntu, como o cls)

vou mandar um mail ao nestor a perguntar se temos pontos (ou perdemos pontos) por usar funcionalidade especificas para um unico sistema operativo...

**Comment by chalkos** [comment]
conversa com o nestor
http://dl.dropbox.com/u/6013254/conversa%20nestor.pdf

TL;DR: façam uma merda de interface simples e apliquem-se no código que é muito mais importante. e de preferência código portátil.

---

Por mim é uma interface normal com um menu em art ascii. consegue-se fazer uma coisa quase tão rápida como os comandos. exemplo:
uma categoria A com subcategorias 1 2 3.
em vez de escreveres A[ENTER], aparecer-te uma lista com as hipoteses que tens no A e depois carregares 2[ENTER]
poderes escrever A2[ENTER] e aparece logo a cena para inserires os dados.

isto é quase tão rápido quanto os comandos, sem obrigar ninguem a aprender comandos

**Comment by danielcarvalhopt** [comment]
Parece-me bem.
